### ISSUE TITLE
Failed to expand primitive type array

### ISSUE THREAD

**Issue by IAM20** [naver/spring-jdbc-plus#112]
primitive array cannot be cast to Object array

```
Caused by: java.lang.ClassCastException: class [B cannot be cast to class [Ljava.lang.Object; ([B and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')
	at com.navercorp.spring.jdbc.plus.support.parametersource.converter.IterableExpandPadding.expandIfIterable(IterableExpandPadding.java:94)
	at com.navercorp.nbaset.spring.data.jdbc.namedparam.NbaseSqlIdentifierParameterSource.getValue(NbaseSqlIdentifierParameterSource.java:110)
	at org.springframework.jdbc.core.namedparam.NamedParameterUtils.substituteNamedParameters(NamedParameterUtils.java:302)
	at com.navercorp.nbaset.spring.jdbc.namedparam.NbaseNamedParameterJdbcTemplate.getPreparedStatementCreatorFactory(NbaseNamedParameterJdbcTemplate.java:86)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.getPreparedStatementCreator(NamedParameterJdbcTemplate.java:424)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.getPreparedStatementCreator(NamedParameterJdbcTemplate.java:402)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:331)
	at com.navercorp.nbaset.spring.data.jdbc.strategy.NbaseInsertStrategyFactory$DefaultNbaseInsertStrategy.execute(NbaseInsertStrategyFactory.java:71)
	at com.navercorp.nbaset.spring.data.jdbc.strategy.NbaseNodeDataAccessStrategy.insert(NbaseNodeDataAccessStrategy.java:122)
	at org.springframework.data.jdbc.core.JdbcAggregateChangeExecutionContext.executeInsertRoot(JdbcAggregateChangeExecutionContext.java:83)
	at org.springframework.data.jdbc.core.AggregateChangeExecutor.execute(AggregateChangeExecutor.java:85)
	... 122 more
```

**Comment by IAM20** [comment]
@chanhyeong Primitive type array 에 대한 Padding 기능을 살릴지 어차피 안되던거 죽일지 고민이 되네요

**Comment by IAM20** [comment]
https://github.com/naver/spring-jdbc-plus/pull/113 되게 만든다면 이런 느낌의 코드가 되겠네요

**Comment by chanhyeong** [comment]
하나 궁금한게 insert 할 때도 padding 하는게 맞는 동작일까요?

**Comment by IAM20** [comment]
@chanhyeong column 에 array 가 있는게 조금 더 신기하긴한데.. 어떤 경우가 있나요??

**Comment by chanhyeong** [comment]
@IAM20
처음 이슈가 제기된 내부 pr 에서 나온건데 따로 공유드리겠습니다

**Comment by IAM20** [comment]
@chanhyeong `Collection` 도 `array` 도 컬럼에 대한 쓰기시 padding 되어버리면 문제가 되는데
컬럼을 `Collection` 으로 표현해야할 이유가 있는지는 모르겠습니다. `BLOB` -> `byte[]` 는 어느정도 이해가 되긴 합니다.

저는 개인적으로는 array 를 아예 제외하고 싶긴 합니다. 살려둔건 어디서 잘 사용하고 있을까봐였긴 했거든요

**Comment by chanhyeong** [comment]
@IAM20
과감하게 가자면 array padding 을 deprecated 로 돌려놓는 것도 방법일 것 같습니다

이게 statement cache 때문으로 알고 있긴 한데 hikaricp 에서는 드라이버에서 제공되는게 있으니 뺐다고 얘기한거도 있고 ([link](https://github.com/brettwooldridge/HikariCP?tab=readme-ov-file#statement-cache))
지금보니 네이밍이 IterableExpandPadding 인데 원래 array 자체는 Iterable 이 아니긴 하니 어색해보이기도 하고요

**Comment by IAM20** [comment]
@chanhyeong 

```SQL
SELECT * FROM order WHERE order_no IN (?, ?)
SELECT * FROM order WHERE order_no IN (?, ?, ?)
```
위 두 개가 다른 PreparedStatement 이기 때문에 제공되는 기능이긴해서
padding 을 진행하여 아래처럼 동일한 PreparedStatement 로 바꿔주어

```SQL
SELECT * FROM order WHERE order_no IN (?, ?, ?, ?)
SELECT * FROM order WHERE order_no IN (?, ?, ?, ?)
```

statement cache 의 hit ratio 를 올려주는 용도이긴 합니다.

**Comment by IAM20** [comment]
> IAM20 과감하게 가자면 array padding 을 deprecated 로 돌려놓는 것도 방법일 것 같습니다
> 

요 방향이 괜찮아보이긴 하네요
